### ISSUE TITLE
Better support for all flavours to single file

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/toolbox#107]
## Description

A number of our existing ports are simply colours listed in the README for users to copy/paste in their configurations, to list a few:

- https://github.com/catppuccin/slack
- https://github.com/catppuccin/fzf
- https://github.com/catppuccin/raycast (I think?)

I'm sure there are others in the organisation too.

I converted our slack port to use whiskers (https://github.com/catppuccin/slack/pull/3) but I came to understand that we can't specify precisely what flavour should be used in the helpers.

## Proposal

The most obvious/naive solution that comes to my mind is something like the following:

```hbs
{{latte red}}, {{frappe red}}, {{macchiato red}}, {{latte red}}
```

but this doesn't necessarily make sense at the minute given that the `FLAVOR` argument is required and should be one flavour.

I'd like to also discuss what "Single File Support" actually means for whiskers. The usecases are demonstrated in the list of ports above - we just want to be able to take in some input, generate colours without picking a single flavour at the start? and then output. 

In the case of Slack, the recent PR for colors iteration (#104) makes me hopeful that we can have something like that for flavours? E.g.

`README.tmpl.md`
```md
---
column_bg: "{{base}}"
weird_colour_that_doesnt_even_show_up_but_slack_inserts_it_anyways: "F8F8FA"
active_item: "{{mauve}}"
active_item_text: "{{base}}"
hover_item: "{{crust}}"
text_color: "{{text}}"
active_presence: "{{mauve}}"
mention_badge: "{{maroon}}"
top_nav_bg: "{{base}}"
top_nav_text: "{{text}}"
---

# Catppuccin for Slack

....

{{ #each flavors as | flavor flavour | }} # kekw
## {{titlecase flavour}}
#{{uppercase column_bg}},#{{weird_colour_that_doesnt_even_show_up_but_slack_inserts_it_anyways}},#{{uppercase active_item}},#{{uppercase active_item_text}},#{{uppercase hover_item}},#{{uppercase text_color}},#{{uppercase active_presence}},#{{uppercase mention_badge}},#{{uppercase top_nav_bg}},#{{uppercase top_nav_text}}
{{/each}}
```

Going off the above, One way to approach this might be adding an `"all"` option for the `FLAVOR` argument which conditionally enables the `flavors` context object? 

Would appreciate people's thoughts and opinions :+1:

**Comment by backwardspy** [comment]
i'm in favour of iteration over flavours rather than flavour helper functions, at least to start with. invoking it with `all` as the flavour name is also exactly what i was thinking.

**Comment by sgoudham** [comment]
Glad to see that we're on the same page! @backwardspy 

Yeah I'm not fond of the individual helper functions but figured I'd include it in this issue for discussion purposes. I think if you need something hardcoded across all of the flavour files... you'd actually just include it at the top in the frontmatter.

I'll have a bash at raising a PR for this if I get around to it, although I'll be mostly focusing on writing up https://github.com/catppuccin/community/pull/12 👍
