### ISSUE TITLE
Add Puccinier into RustSec Advisory Database

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/toolbox#155]
Puccinier is now marked as deprecated on [crates.io](https://crates.io/crates/puccinier) and should be marked as `unmaintained` in https://github.com/rustsec/advisory-db.

Helpful links:
- https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md
- https://github.com/RustSec/advisory-db/blob/main/CONTRIBUTING.md

**Comment by rubyowo** [comment]
My PR to rustsec was merged. this can be closed now.

**Comment by sgoudham** [comment]
Closed as https://github.com/rustsec/advisory-db/pull/1927 was raised by @rubyowo and merged.
