### ISSUE TITLE
Whiskers doesn't read frontmatter in files encoded as UTF-8 with BOM

### ISSUE THREAD

**Issue by James-McK** [catppuccin/toolbox#178]
Only noticed this because one of the files I was working with was already encoded as UTF-8 with BOM for some reason, and was giving errors about variables that I defined in the frontmatter not being found.

eg

```tera
---
whiskers:
  version: 2.0.2
accent: "mauve"
---

accent: {{ accent }}
```

encoded as UTF-8 with BOM gives the output

```
Warning: No Whiskers version requirement specified in template.
This template may not be compatible with this version of Whiskers.

To fix this, add the minimum supported Whiskers version to the template frontmatter as follows:

---
whiskers:
    version: "2.0.2"
---

Error: Single-output render failed

Caused by:
    0: Template render failed
    1: Failed to render 'test.tera'
    2: Variable `accent` not found in context while rendering 'test.tera'
```

This really isn't a big deal, I've already easily re-encoded the files as just UTF-8, but it'd be nice if whiskers either gave a more useful error message, or read the frontmatter, in this case

**Comment by backwardspy** [comment]
interesting issue, thanks for raising this. perhaps we can attempt to detect encoding and, if it succeeds, use that to load & write (where applicable) the files.

**Comment by backwardspy** [comment]
this is fixed from a file _reading_ perspective. writing other encodings is covered under #181. thanks again for raising this issue!
