### ISSUE TITLE
Catwalk: Side-by-Side Grid Layout request.

### ISSUE THREAD

**Issue by isabelincorp** [catppuccin/toolbox#20]
So that instead of (2x2)
```
A  B
A  B

C  D
C  D
```
It would be (4x1) 
```
A B C D
A B C D
```

This would work really well with mobile screenshots, as currently catwalk isn't ideal for mobile screenshots.

**Comment by isabelincorp** [comment]
Perhaps maybe implementing a dimension variable into --layout grid could solve this so for example for normal grid (ideal for desktop screenshots) it would be `--layout grid 2,2` then for the mobile grid it would be `--layout grid 4,1`, another possible layout could be `--layout grid 1,4` that gives you which could be used for ports like [st](https://github.com/catppuccin/st)
```
AA
BB
CC
DD
``` 
(variables are `horizontal,vertical`)

**Comment by JoshPaulie** [comment]
I'd be happy to implement this, but the specifics are tripping me up.

Wouldn't a 2x2 look like
```
A B
C D
```

While 4x1 would look like
```
A B C D
```

**Comment by isabelincorp** [comment]
Yep pretty much.

**Comment by nekowinston** [comment]
Impemented in catwalk v1.2.0.
