### ISSUE TITLE
Improvement for Puccinier: Make it convert the name of flavours.

### ISSUE THREAD

**Issue by Sourcastic** [catppuccin/toolbox#21]
All I'm proposing is a tiny improvement for puccinier that converts "Mocha" and other variants (lowercase, catppuccin-mocha etc) to the name of the flavours you're pucciniering to. This would be useful for converting metadata where you would otherwise have to go through all the flavours and convert it yourself. Thoughts?

**Comment by nekowinston** [comment]
Closing because of #66
