### ISSUE TITLE
Add `--list-flavors` and `--list-accents`

### ISSUE THREAD

**Issue by uncenter** [catppuccin/toolbox#210]
These flags would output a list (in various formats maybe, with `-o`) of the flavors and accents in Catppuccin. Would simplify something like https://github.com/r58Playz/ctp-devtools/blob/74bccc4f5922a9070013ab951e9d9cbfc678d532/generate.sh#L3-L4.

**Comment by isabelroses** [comment]
> These flags would output a list (in various formats maybe, with `-o`) of the flavors and accents in Catppuccin. Would simplify something like [r58Playz/ctp-devtools@`74bccc4`/generate.sh#L3-L4](https://github.com/r58Playz/ctp-devtools/blob/74bccc4f5922a9070013ab951e9d9cbfc678d532/generate.sh#L3-L4).

would using a .tera file not fix this?

**Comment by uncenter** [comment]
No, Tera matrices are already used in that script linked above. The for loop is needed to symlink other files for every flavor and accent.
