### ISSUE TITLE
whiskers: `rgb(a)` helpers disagree with original hex because of hex -> hsla -> rgb conversion

### ISSUE THREAD

**Issue by alchzh** [catppuccin/toolbox#90]
Color wise it's imperceptible, but could lead to odd results on a documentation or a README.

Example:

```bash
$ echo "{{red}} {{rgb red}} {{hsl red}}" | whiskers - latte
d20f39 rgb(211, 15, 58) hsl(347, 87%, 44%)
```

More precisely, `d20f39` is `rgb(210, 15, 57)`

**Comment by backwardspy** [comment]
thanks for reporting this @alchzh, it should be fixed now!
